// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResturantWebApi.Data;

#nullable disable

namespace ResturantWebApi.Migrations
{
    [DbContext(typeof(ResturantDbContext))]
    partial class ResturantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ResturantWebApi.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ResturantWebApi.FoodItem", b =>
                {
                    b.Property<int>("foodItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("foodItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("foodItem");

                    b.ToTable("FoodItems");
                });

            modelBuilder.Entity("ResturantWebApi.Models.OrderDetail", b =>
                {
                    b.Property<long>("orderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("foodItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("foodItemPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<long>("orderMasterId")
                        .HasColumnType("bigint");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("orderDetailId");

                    b.HasIndex("foodItemId");

                    b.HasIndex("orderMasterId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("ResturantWebApi.Models.OrderMaster", b =>
                {
                    b.Property<long>("orderMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("customerId")
                        .HasColumnType("int");

                    b.Property<decimal>("gTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("orderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("pMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("orderMasterId");

                    b.HasIndex("customerId");

                    b.ToTable("OrderMasters");
                });

            modelBuilder.Entity("ResturantWebApi.Models.OrderDetail", b =>
                {
                    b.HasOne("ResturantWebApi.FoodItem", "FoodItem")
                        .WithMany()
                        .HasForeignKey("foodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResturantWebApi.Models.OrderMaster", "OrderMaster")
                        .WithMany("OrderDetails")
                        .HasForeignKey("orderMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("OrderMaster");
                });

            modelBuilder.Entity("ResturantWebApi.Models.OrderMaster", b =>
                {
                    b.HasOne("ResturantWebApi.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("customerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ResturantWebApi.Models.OrderMaster", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
